enum MidaVehicle {
    PETIT
    MITJA
    GRAN
}

abstract Class Vehicle {
- matricula : String
- mida : MidaVehicle

+ getMatricula() : String
+ getMida() : MidaVehicle
}

Vehicle "1" --> "1" PlacaAparcament : aparcat


Class Motocicleta {
+ Motocicleta(matricula : String)
}

Class Cotxe {
+ Cotxe(matricula : String)
}

Class Camio {
+ Camio(matricula : String)
}

Vehicle <-- Motocicleta
Vehicle <-- Cotxe
Vehicle <-- Camio


abstract Class PlacaAparcament {
    - numero : int
    - estat : boolean
    - vehicleAparcat : Vehicle
    - coordenades : Coordenada[]
    - midaMaxima : MidaVehicle

    + aparcar(vehicle : Vehicle) : void
    + desaparcar() : void
    + estaLliure() : boolean
}

PlacaAparcament "1" --> "*" Coordenada : té


Class Coordenada {
    - y : double
    - x : double
}


Class PlacesParking {
    - places : ArrayList<PlacaAparcament>
    - tickets : ArrayList<Ticket>
    + PREU_MINUT : double

    + afegirPlaca(placa : PlacaAparcament) : void
    + aparcar(vehicle : Vehicle) : Ticket
    + desaparcar(ticket : Ticket) : double
    + buscarTicket(id : int) : Ticket
    + mostrarEstat() : void
}

PlacaAparcament "1" -- "*" PlacesParking : té
PlacesParking "1" -- "*" Ticket : gestiona


class PlacaCompacta {
}

class PlacaRegular {
}

class PlacaGran {
}

PlacaAparcament <-- PlacaCompacta
PlacaAparcament <-- PlacaRegular
PlacaAparcament <-- PlacaGran


Class Ticket {
    - numero : int
    - vehicle : Vehicle
    - placa : PlacaAparcament
    - entrada : LocalDateTime
    - sortida : LocalDateTime

    + getVehicle() : Vehicle
    + getPlaca() : PlacAparcament
    + setSortida() : void
    + calcularMinuts() : long
}
